/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia5.Vistas;

import javax.swing.JOptionPane;
//import guia5.AccesoADatos.*;
/**
 *
 * @author dev0
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumno = new javax.swing.JMenu();
        jMFormAlumno = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        jMFormularioMateria = new javax.swing.JMenuItem();
        jMAdministracion = new javax.swing.JMenu();
        jMManejoIns = new javax.swing.JMenuItem();
        jMManipNotas = new javax.swing.JMenuItem();
        jMConsultas = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        escritorio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                escritorioPropertyChange(evt);
            }
        });

        jMAlumno.setText("Alumno");

        jMFormAlumno.setText("Formulario de Alumno");
        jMFormAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFormAlumnoActionPerformed(evt);
            }
        });
        jMAlumno.add(jMFormAlumno);

        jMenuBar1.add(jMAlumno);

        jMMateria.setText("Materia");

        jMFormularioMateria.setText("Formulario de Materia");
        jMFormularioMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFormularioMateriaActionPerformed(evt);
            }
        });
        jMMateria.add(jMFormularioMateria);

        jMenuBar1.add(jMMateria);

        jMAdministracion.setText("Administracion");

        jMManejoIns.setText("Manejo de Inscripciones");
        jMManejoIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMManejoInsMouseClicked(evt);
            }
        });
        jMAdministracion.add(jMManejoIns);

        jMManipNotas.setText("Manipulacion de Notas");
        jMAdministracion.add(jMManipNotas);

        jMenuBar1.add(jMAdministracion);

        jMConsultas.setText("Consultas");

        jMenuItem5.setText("Alumnos por Materia");
        jMConsultas.add(jMenuItem5);

        jMenuBar1.add(jMConsultas);

        jMSalir.setText("Salir");
        jMSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMSalirMousePressed(evt);
            }
        });
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMFormAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFormAlumnoActionPerformed
    escritorio.removeAll();
    escritorio.repaint();
    
    FormularioAlumno f = new FormularioAlumno();
    f.setVisible(true);
    escritorio.add(f);
    escritorio.moveToFront(f);
    }//GEN-LAST:event_jMFormAlumnoActionPerformed

    private void jMFormularioMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFormularioMateriaActionPerformed
      escritorio.removeAll();
      escritorio.repaint();
      FormularioMaterias f = new FormularioMaterias();
      f.setVisible(true);
      escritorio.add(f);
      escritorio.moveToFront(f);
    }//GEN-LAST:event_jMFormularioMateriaActionPerformed

    private void jMManejoInsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMManejoInsMouseClicked
       escritorio.removeAll();
       escritorio.repaint();
        FormularioConsulta fc = new FormularioConsulta();
        fc.setVisible(true);
        escritorio.add(fc);
        escritorio.moveToFront(fc);
    }//GEN-LAST:event_jMManejoInsMouseClicked

    private void escritorioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_escritorioPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_escritorioPropertyChange

    private void jMSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSalirMousePressed
        JOptionPane.showMessageDialog(this,"Desea cerrar el programa?");
        System.exit(0);
    }//GEN-LAST:event_jMSalirMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuPrincipal().setVisible(true);
        }); 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMAdministracion;
    private javax.swing.JMenu jMAlumno;
    private javax.swing.JMenu jMConsultas;
    private javax.swing.JMenuItem jMFormAlumno;
    private javax.swing.JMenuItem jMFormularioMateria;
    private javax.swing.JMenuItem jMManejoIns;
    private javax.swing.JMenuItem jMManipNotas;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
        
    
        
                


        
}



